### ISSUE TITLE
Audio not playing on Iphone and Android

### ISSUE THREAD

**Issue by umairkhantraffic** [emotionLoop/visualCaptcha#14]
I have checked the demo (http://demo.visualcaptcha.net/) on my Sony Xperia Z1 (4.4.4) Samsung S5, Iphone 5s and Iphone 6 but whenever i click on audio it does not play any sound

**Comment by BrunoBernardino** [comment]
Hi @umairkhantraffic have you checked your multimedia audio volume? I just tested on an iPhone 5S, iPhone 6 and a Nexus 5, all working fine on chrome (iOS/Android) and safari (iOS).

**Comment by umairkhantraffic** [comment]
Hi Bruno,

Thanks for prompt reply. Yes i have checked and my multimedia volume is full. Just to make sure, i have also tried recaptcha demo http://www.google.com/recaptcha/api2/demo and checked the audio captcha and its playing fine. 

I also tried by plugging in the headphones but the result is same and no voice. The captcha itself is working fine, its just the audio which is not playing.

For your reference i am attaching here the screenshot of my chrome version on sony xperia z1 running on android 4.4.4.

Please let me know if you need more details
![screenshot_2015-01-28-12-53-59](https://cloud.githubusercontent.com/assets/567480/5934145/d9c168aa-a6ec-11e4-856e-8fa0a6d4a470.png)

**Comment by BrunoBernardino** [comment]
Can you post details about your iPhone? I understand how on Android things can get messy (though they shouldn't, since these are HTML5 APIs), but I can't understand how it wouldn't work on a couple of iPhones over there and work over here.

**Comment by umairkhantraffic** [comment]
Hi Bruno,

Please ignore, its not an issue. I did further investigation and found that audio was being blocked by a network firewall only for devices IP. I apologize.

**Comment by BrunoBernardino** [comment]
Great to hear you solved it!
