### ISSUE TITLE
Integration with ADF Portal application. Jdev 11g.

### ISSUE THREAD

**Issue by manojcute009** [emotionLoop/visualCaptcha#15]
Hi All,

I want to integrate this captcha with my adf application. Please help me in this. If possible provide me a jar file. So that this can be added to application and can be used. Please mail me solution at manojcute009@gmail.com

**Comment by BrunoBernardino** [comment]
Hi @manojcute009 I've seen you posted this request in a few places, but I'll just answer it here, if that's fine.

We don't officially support Java, but you can try to find help on a community-supported version, at https://github.com/bdotzour/visualCaptcha-java

**Comment by manojcute009** [comment]
Hi,
Thanks BrunoBernardino.
I will post my query there. :)
