### ISSUE TITLE
Cakephp Plugin

### ISSUE THREAD

**Issue by hashmode** [emotionLoop/visualCaptcha#16]
Hi,

I just uploaded the plugin for cakephp, thought that it might be helpful to add into `Unofficial versions` section
here is the link
https://github.com/hashmode/VisualCaptcha-Cakephp-Plugin

Thanks

**Comment by BrunoBernardino** [comment]
Thank you so much for this, added to https://github.com/emotionLoop/visualCaptcha/blob/master/README.md#unofficial-versions-created-by-community-members !
