### ISSUE TITLE
Contact Form 7 integration?

### ISSUE THREAD

**Issue by mehtuus** [emotionLoop/visualCaptcha#19]
Please forgive me if this is not the correct place to post this, but...

I am wondering if there has been any further development on integrating visualCaptcha with **Contact Form 7**? I did find the [sudo-solution](http://wordpress.org/support/topic/integration-with-contact-form-7-9?replies=5#post-5749633) from the FAQ page, but having to recode it every-time the plugin is updated leaves a bad taste.

**Comment by BrunoBernardino** [comment]
Hi @mehtuus I don't believe the developers at **Contact Form 7** are interested in integrating visualCaptcha.

I haven't looked into anything WordPress for quite a long time, but except they've since added default/standard hooks for showing content, there's no customization that won't depend on their side we can do.

**Comment by BrunoBernardino** [comment]
If you have such information for me, feel free to add it here, as I will be doing some updates for visualCaptcha (in all components/front-end/back-end) in July.

**Comment by mehtuus** [comment]
Thanks @BrunoBernardino for the information. I have a question regarding this over on the [Contact Form 7](https://wordpress.org/support/topic/hooks-for-3rd-party-captcha) WP support page as well. I get the feeling too that the developer there has no interest in extending his plugin.

Do you have any recommendations on a decent contact form that plays well with visualCaptcha?

**Comment by BrunoBernardino** [comment]
I haven't worked with WordPress in quite a long time, so I don't have any good recommendation.

Anything that supports hooks without having to code them in will work well. You'll simply need to add the hooks in the visualCaptcha interface.

**Comment by mehtuus** [comment]
OK. Thanks.
