### ISSUE TITLE
100% break rate

### ISSUE THREAD

**Issue by PierreBarre** [emotionLoop/visualCaptcha#20]
Hello,

I made a script that is breaking visualCaptcha with a rate of 100%
Of course, this is required to build a database of the images used by the website. This can be time consuming but [most websites which makes the use of visualcaptcha are using the default images anyway](https://www.google.com/search?q=%22Type+below+the+answer+to+what+you+hear%22&oq=%22Type+below+the+answer+to+what+you+hear%22&ie=UTF-8).

https://github.com/PierreBarre/visualCaptchaBreaker

**Comment by BrunoBernardino** [comment]
Hi @PierreBarre thanks for submitting this!

Wow. Yeah, one of the points for visualCaptcha is to allow people customizing the images, their names, etc. but most don't change that indeed.

One thing I'd note is that script would need tweaks for each website you encounter. You're assuming it's always a PHP setup with the default session name (though you'd only need to look for what the session cookie name is).

I'm more curious about the resources needed to run those visual comparisons. The images are small, definitely, but still, could you easily/quickly do a 1000 requests, for example?

Anyway, what would you say the solution for this is? I've thought about creating a "generator" which would easily allow people to define questions and images for download and setup, but it would require people to act on it, which I'm not so sure they'd do.

**Comment by PierreBarre** [comment]
n fact, in the present state, that would be required to adapt the script to every website we would want to attack, but we can also just send all the cookies we got so we don't bother with "which cookie is the session one?"
The CPU consumption issue is a good point, I haven't thought too much about that.
I benchmarked using this script:

    from PIL import Image
    import multiprocessing
    
    
    def image_diff_percentage(image1, image2):
        image1 = Image.open('0.png')
        image2 = Image.open('1.png')
    
        pairs = zip(image1.getdata(), image2.getdata())
    
        if len(image1.getbands()) == 1:
            dif = sum(abs(p1-p2) for p1, p2 in pairs)
        else:
            dif = sum(abs(c1-c2) for p1, p2 in pairs for c1, c2 in zip(p1, p2))
    
        ncomponents = image1.size[0] * image2.size[1] * 3
        percentage = abs((dif / 255.0 * 100) / ncomponents)
    
        return percentage

    if __name__ == '__main__':
        pool = multiprocessing.Pool()
        for _ in range(100000):
            pool.apply_async(image_diff_percentage, (_,))
            print('compared {} couples of images'.format(_))
        pool.close()
        pool.join()
    
### Results

It took ~7 seconds on a Intel® Xeon® E3 1220 v2 to compare 100 000 couples of images (14 000 per second). I assume the limitation is more the network or the computing power which is allocated to run the website.
I would have though of two solutions, 
- Permitting the addition of multiple words to describe one image, that would add some pain for the spammer.
- Adding a way more noise on the images

**Comment by BrunoBernardino** [comment]
If you need a lot of security, ReCaptcha is a pretty good choice, visualCaptcha is not in a competition for security, but usability.

Google has done something very nice with the checkbox thing, but it doesn't _always_ show up. Eventually I imagine visualCaptcha won't be necessary, but the need for focusing on UX is real.

As for adding noise in the images, it defeats the purpose UX-wise.

More than one word to describe the image is pretty good.

I've been thinking of a v6, where there would be no images, only the audio option, which is accessible by default and much harder to bypass. Coupled with some app to generate the audio.json and the audio files.

That would definitely break your app, but I'm wondering if an audio-only captcha is something people would enjoy using... Maybe if the question is typed as well it would work?

What do you think?

**Comment by PierreBarre** [comment]
I understand that was not the point of visualCaptcha to provide *a lot* of security. But, I think there is a world between a break rate of a few percents and a 100% break rate.

You are right about the UX but not doing this compromise would mean visualCaptcha would be something that bother real users while doing nothing with bots.

I believe an audio-only captcha would be a bad thing, especially when people are on the move in public transports or just in presence of other peoples, they can't always play sounds without disturbing the others. Hence, not all the users have the hardware required to listen to sounds. That's also about user's convenience, for instance, if he is listening to music while trying to register to your website, I don't think that would please him to have first to pause his listening to hear yours.

**Comment by BrunoBernardino** [comment]
I see, that makes sense.

Maybe there's no place in the world for a new visualCaptcha version anymore, now that Google has the checkbox thing.

**Comment by PierreBarre** [comment]
I would not say there is no place for another solution because reCaptcha is there.

There are a few issues running reCaptcha anyway, a little list that comes to my mind:

- You don't control whoever can see the captcha an who can't see it (a few countries or a few networks may not like google too much).
- You share a lot of information with google
- You are not controlling the availability (ok, that's least of an issue with google but still)
- You don't know when the product will ends its life (hello google reader and tons of services google has discontinued)

The new version of reCaptcha is very good UX wise, it tries to minimise the impact on the real user while being a real pain for bots. It's quite possible to do a similar product which accomplishes the same goals with not too much effort.

**Comment by BrunoBernardino** [comment]
Ok, let me play devil's advocate here:

- Google might be blocked, but not reCaptcha
- Right. And [the new method actually makes this worse](https://recaptcha.sucks)
- I'd say it's a non-issue :)
- It's spread through way too many places for Google to just shut it down like that. I think.
- Hardly happens, though it's not false
- Yeah, but... have you read them? :)

So. I'm left with a bit of a tough choice...

1. Launching a new version will be very time-consuming (updating all libraries et all), and I will not have the time to make that kind of effort in the next 6 months.
2. I don't see an _obvious_ way that will keep a great UX and improve security substantially from what's there now (which doesn't rely on a SaaS-like model)
3. While there are no _great_ alternative to reCaptcha, it serves the need most people have. If you're technical, there's many ways you can create a custom plan for avoiding bots on your apps. Also, many options to install and customize, just like visualCaptcha.

It seems to me it does not make sense to launch a new visualCaptcha version.

Thoughts?

**Comment by PierreBarre** [comment]
- Since the recaptcha scripts are served from the google.com, running on the google's ips ranges, the distinction would be quite difficult to do.
- In fact.
- Google already discontinued very popular services, I wouldn't bet too much on this.
- Of course.
- Better to do so, if you don't want to be the victim of the previous point :-)

Unfortunately, I think you're true, visualCaptcha is appealing because it's no too much a pain to complete for a user, but if that's the case for the human, that's here even easier for the robot to do the same.

I don't think you can really enhance visualCaptcha anymore security wise (because security through obscurity is not a solution); the product is suffering of it's inherent design.

Like you said, doing something that is easy for the user while being complicated for the machine would be hard excluding a SaaS model. So, no, I don't think it would be worth it to build another version of visualCaptcha, it would probably fall into one of the points mentioned above even with a new design.

**Comment by BrunoBernardino** [comment]
- Right, I haven't looked at how it works in a long time, it used to be reCaptcha's own domain.

So, I suppose I'll close this, then.

Let me know if you think of something that could solve this!

**Comment by CrazyPython** [comment]
@BrunoBernardino if we have a 100% break rate, then why have a CAPTCHA at all? It's pretty much security through obscurity. You could use real world images and only prompt when the user appears suspicious.

**Comment by BrunoBernardino** [comment]
@CrazyPython I'm happy to review and accept a PR with such capabilities, or link to such a project. At this moment I'm not in a position to completely rework visualCaptcha when it's a valid option when reCaptcha isn't used (which, to me, in their current state, poses as a much better option).

**Comment by CrazyPython** [comment]
@BrunoBernardino This issue is a manifestation of my theoretical problem.
