### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by highacid** [emotionLoop/visualCaptcha#22]
Is the plugin translated in any other languages then English? If so how can one translate it the easiest way. Thanks a lot.

**Comment by BrunoBernardino** [comment]
Hi @highacid !

Yeah, it's been translated in many other languages (including [Japanese](https://github.com/NetCommons3/VisualCaptcha)).

Here's a Portuguese sample for the front-end: https://github.com/emotionLoop/visualCaptcha-frontend-core#localization

In the back-end, you just need to translate the .json files.
