### ISSUE TITLE
Asking for more secure captcha (ex. reCaptcha) when user gets incorrect answer ~2 times in a row

### ISSUE THREAD

**Issue by CrazyPython** [emotionLoop/visualCaptcha#26]
Clearly if the user can't recognize basic object well he/she*'s a robot.

*I'm not even sure robots have genders...

**Comment by BrunoBernardino** [comment]
Don't discriminate ;)

What you're suggesting can be easily implemented at the server-side, I don't see a good reason to make it "mandatory" for everyone and with the sleuth of possible server/code/framework combinations, it'd be almost impossible to target a decent percentage.

Thank you for the suggestion!
