### ISSUE TITLE
Demo of visualCaptcha doesn't provide correct symbol.

### ISSUE THREAD

**Issue by thundergolfer** [emotionLoop/visualCaptcha#28]
I clicked on your demo from the visualCaptcha site, and it seems to ask for the impossible.
![visual_captcha](https://cloud.githubusercontent.com/assets/12058921/18009188/8708fef2-6bee-11e6-81dd-5057c98f99d6.PNG)

I'm either crazy or none of those symbols are sunglasses. I tried refreshing and re-entering the demo, but neither of these things changed the request away from *sunglasses*.

**Comment by BrunoBernardino** [comment]
Hi @thundergolfer indeed the DEMO no longer has a functional back-end (we didn't want to have those server costs) and the demos we have on GitHub should allow for a simple and quick clone and setup to see it working.

That's why we have the "(won't work)" in the "Submit" button, but I'm glad to take suggestions in making that more clear!

**Comment by thundergolfer** [comment]
@BrunoBernardino 

That makes more sense. I certainly took the "Won't work" to refer to the form submission part of the demo and not the actual captcha-backend. 

I would probably change it to make it clear that they whole demo is non-functional. Or just remove it?

Cheers

**Comment by BrunoBernardino** [comment]
Will be tracking in https://github.com/emotionLoop/visualCaptcha-demo/issues/1

Thanks!

**Comment by MrJulz** [comment]
Agreed: Having "touch or click the sunglasses" but no actual sunglasses does not exactly enable the demo to create a fine impression.

Even without the backend, perhaps just a simple yet static javascript implementation, with a working button would better server the purpose of demonstrating this idea?  (The idea is good)

**Comment by BrunoBernardino** [comment]
Great point! I've updated the image name.
