### ISSUE TITLE
Crazy to let the client side determine image count

### ISSUE THREAD

**Issue by Saeven** [emotionLoop/visualCaptcha#6]
Try this code on your demo page

```
        var captchaEl = $( '#sample-captcha' ).visualCaptcha({
            imgPath: 'img/',
            captcha: {
                numberOfImages: 1
            }
        } );
        var captcha = captchaEl.data( 'captcha' );
```

The answer will necessarily be the leftmost image.

**Comment by CrazyPython** [comment]
@BrunoBernardino If reCaptcha doesn't prompt users for a captcha most of the time (most of the time its just checking a checkmark), and it's easier to implement (less customization), then why use visualCaptcha?

**Comment by BrunoBernardino** [comment]
@CrazyPython That's a great question. Apparently there are some privacy concerns and others that have been debated [in this comment](https://github.com/emotionLoop/visualCaptcha/issues/20#issuecomment-165857198) but I'd personally recommend reCaptcha if you have a _real_ security threat/concern. For most situations, visualCaptcha will do just fine, though.

**Comment by CrazyPython** [comment]
@BrunoBernardino A decent hacker would just use a headless browser framework (ex. Phantom.JS) and set the image count to 2, so he/she could try four times and get in.
