### ISSUE TITLE
Too easy to crack

### ISSUE THREAD

**Issue by ghost** [emotionLoop/visualCaptcha#8]
Sorry guys but your captcha very easy to crack 1/10.

First need create database on your images:
- then simple create fingerprint of all images eq:
  - red dots are saved color position
  - Then just compare all images from database

![lamers](https://cloud.githubusercontent.com/assets/908583/3374121/7f068306-fbba-11e3-9dfe-0a08964a8d39.png)

This is some kind of joke ?

**Comment by CrazyPython** [comment]
@BrunoBernardino A hacker with four hours could break your security y downloading something like ConvNetJS and using it to recognize images. No GPU required.

**Comment by BrunoBernardino** [comment]
I can imagine that's possible for the default install everyone sees. I'd recommend those people use something like reCaptcha.
